#! /bin/sh

## General settings

# Set config directories
BSPDIR="$HOME/.config/bspwm/"
BARDIR="$HOME/.config/polybar/"

# Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

## Autostart

# Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Applications
exec $BSPDIR/scripts/autostart &

# Low battery warning
exec $BSPDIR/scripts/battery-notify &

#
## Appearance settings
#

# Colors
bspc config focused_border_color        "#61afef"
bspc config normal_border_color         "#1e2127"
bspc config urgent_border_color         "#e06c75"

# Borders and gaps
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#
## Window rules
#

bspc rule -a firefox desktop=^2
bspc rule -a Thunar state=floating
