#!/usr/bin/env lua

-- General settings


local BSPDIR = os.getenv("HOME") .. "/.config/bspwm/"


-- Exports

os.execute(BSPDIR .. "scripts/exports.lua &")


-- Display settings

os.execute(BSPDIR .. "scripts/display-layout.lua &")
os.execute(BSPDIR .. "themes/polybar.sh &")

-- Autostart

-- Sxhkd
if os.execute("pgrep -x sxhkd > /dev/null") ~= 0 then
  os.execute("sxhkd &")
end

-- Applications
os.execute(BSPDIR .. "scripts/applications.lua &")

-- Dunst
os.execute(BSPDIR .. "scripts/bspdunst.lua &")

-- Battery notifications
os.execute(BSPDIR .. "scripts/battery-notify.lua &")

-- Appearance settings

-- Colors
local BSPWM_FBC = "#83a598"
local BSPWM_NBC = "#282828"
local BSPWM_ABC = "#83a598"
local BSPWM_PFC = "#98971a"

-- Gaps and borders
local BSPWM_BORDER = "2"
local BSPWM_GAP = "12"
local BSPWM_SRATIO = "0.50"

-- Apply settings
os.execute("bspc config focused_border_color " .. BSPWM_FBC)
os.execute("bspc config normal_border_color " .. BSPWM_NBC)
os.execute("bspc config active_border_color " .. BSPWM_ABC)
os.execute("bspc config presel_feedback_color " .. BSPWM_PFC)

os.execute("bspc config border_width " .. BSPWM_BORDER)
os.execute("bspc config window_gap " .. BSPWM_GAP)
os.execute("bspc config split_ratio " .. BSPWM_SRATIO)

os.execute("bspc config borderless_monocle true")
os.execute("bspc config gapless_monocle true")
os.execute("bspc config paddingless_monocle true")
os.execute("bspc config single_monocle false")
os.execute("bspc config focus_follows_pointer true")
os.execute("bspc config presel_feedback true")

-- Window rules

os.execute(BSPDIR .. "scripts/rules.lua &")
