#! /bin/sh

#
## General settings
#

# Set config directories
BSPDIR="$HOME/.config/bspwm/"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

#
## Display settings
#

# External monitor (Nvidia)
if [[ $(xrandr -q | grep "HDMI-0 connected") ]];
   then
      xrandr --output HDMI-0 --mode 1920x1080 --pos 0x0 --rotate normal \
             --output eDP-1-1 --mode 1920x1080 --pos 0x1080 --rotate normal 
      bspc monitor HDMI-0 -d 1 2 3 4 5
      bspc monitor eDP-1-1 -d 6 7 8 9 10
      exec $BSPDIR/themes/polybar.sh &
fi

# Internel monitor (Nvidia)
if [[ $(xrandr -q | grep "HDMI-0 disconnected") ]];
   then
      xrandr --output eDP-1-1 --mode 1920x1080 --pos 0x0 --rotate normal \
             --output HDMI-0 --off 
      bspc monitor eDP-1-1 -d 1 2 3 4 5
      exec $BSPDIR/themes/polybar.sh &
fi

# Internal monitor (Intel)
if [[ $(xrandr -q | grep "eDP1") ]];
  then
    bspc monitor eDP1 -d 1 2 3 4 5
    exec $BSPDIR/themes/polybar.sh &
fi

#
## Autostart
#

# Sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Applications
exec $BSPDIR/scripts/autostart &

# Dunst
exec $BSPDIR/scripts/bspdunst.sh &

# Battery notifications
exec $BSPDIR/scripts/battery-notify.sh &

#
## Appearance settings
#

# Colors
BSPWM_FBC='#e02f1b'
BSPWM_NBC='#190c0e'
BSPWM_ABC='#e02f1b'
BSPWM_PFC='#8abd68'

# Gaps and borders
BSPWM_BORDER='2'
BSPWM_GAP='12'
BSPWM_SRATIO='0.50'

# Apply settings
bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

#
## Window rules
#

bspc rule -a firefoxdeveloperedition desktop=^2
bspc rule -a Thunar state=floating
bspc rule -a zoom desktop=^3
