#! /bin/sh

bsp-layout set tile 1
bsp-layout set tile 2
bsp-layout set tile 3
bsp-layout set tile 4
bsp-layout set tile 5
bsp-layout set tile 6
bsp-layout set tile 7
bsp-layout set tile 8
bsp-layout set tile 9
bsp-layout set tile 10
